# Generated by Django 3.0 on 2019-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
                ('num_events', models.IntegerField()),
                ('filter', models.TextField(max_length=1000)),
                ('alert', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=400)),
            ],
        ),
    ]
