# Generated by Django 3.0 on 2019-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20191212_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='runstatus',
            field=models.CharField(default='running', max_length=100),
        ),
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
